### ISSUE TITLE
Re-factor how spotlight animation is preformed.

### ISSUE THREAD

**Issue by Hanson-Jay** [byuitechops/planet-simulator#19]
Right now spotlight animations to move the spotlight and to re-size it are done with an interval. I know for sure the movement can be done with jQuery animation but ran into a problem using jQuery for the size of the spotlight. Look into getting that to work with jQuery as well.

**Comment by eljulander** [comment]
If it ain't broke, don't fix it.

**Comment by eljulander** [comment]
Jumped the gun. We need to rewrite using svg.js for the animations.

**Comment by eljulander** [comment]
Due to time limitations, and to save server calls, we are going to close this issue for now and leave the script as-is.
