### ISSUE TITLE
add custom text and order to spotlight animation with next step button

### ISSUE THREAD

**Issue by meeple142** [byuitechops/planet-simulator#60]
Classic case of :
>It is well known that software development is often a wicked problem: we know if we have solved it only when we have developed it.

**Comment by meeple142** [comment]
see this for an idea on how the CSV could work. i only expanded the initial row in this CSV but they would all need it. 
https://github.com/byuicampuscd/planet-simulator/blob/master/csvs/Idea%20For%20new%20style.csv

**Comment by meeple142** [comment]
could just leave them blank on the left and error check but this way the teachers will have a better chance to do it the first time

**Comment by eljulander** [comment]
Resolved with commit 34a8a5c48e61383201fdbf2250d7f32a26e93200
