### ISSUE TITLE
Fix spot light shape

### ISSUE THREAD

**Issue by meeple142** [byuitechops/planet-simulator#82]
some of the spotlight locations are off a bit or the wrong shape. the spot light should hug the item as much  as possible.

**Comment by eljulander** [comment]
Custom spotlight fitting is done in this function
`function getCurrentAnimationBounds(index) {...}`
I created the "yolo" csv to help test the lights.

**Comment by eljulander** [comment]
This was fixed with commit 4c56f5496ea0c311cedf3e7b6cb9e309c164698f
